from typing import List, Optional

class BitLlamaConfig:
    vocab_size: int
    hidden_dim: int
    num_layers: int
    inner_lr: float
    n_gpu_layers: Optional[int]

    def __init__(self, vocab_size: int, hidden_dim: int, num_layers: int, inner_lr: float) -> None: ...

class BitLlama:
    def __init__(self, config: BitLlamaConfig, checkpoint_path: str, device: Optional[str] = None) -> None: ...
    def forward(self, token_id: int) -> List[float]: ...
    def generate(self, prompt: str, max_tokens: int) -> str: ...
    def generate_tokens(self, start_tokens: List[int], max_new_tokens: int) -> List[int]: ...

class PyTrainer:
    def __init__(self, config: BitLlamaConfig, checkpoint_path: Optional[str] = None, device: Optional[str] = None) -> None: ...
    def set_learning_rate(self, lr: float) -> None: ...
    def train_step(self, py_input_ids: List[int], py_targets: List[int]) -> float: ...
    def save_checkpoint(self, path: str) -> None: ...
