@echo off
echo Initializing MSVC Environment...
call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
echo Launching Bit-Llama GUI (High-Performance Mode)...
cargo run --release --features cuda --bin bit_llama -- gui
